M48
; DRILL file {KiCad 9.0.6} date 2025-12-28T21:38:20+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-28T21:38:20+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X111.11Y-164.895
X116.89Y-164.895
X123.11Y-164.895
X128.89Y-164.895
M30
